### ISSUE TITLE
Very important question

### ISSUE THREAD

**Issue by Ajin695** [je-suis-tm/je-suis-tm#12]
Hello! I'm Ajin. First of all i would like to congratulate with you for your job, you are amazin!
Secondly: i am approaching to the script and coding and i was studying, in Complex network, Barabasi Albert model. I wanted to run your file with Visual Studio Code but i am not able. How can i convert it into a Python code and run it? I am particular interested to the part of the power law study. i hope you can let me know! in any case, i thank you a lot. Best regards

**Comment by je-suis-tm** [comment]
Hi Ajin, thx for the visit. Not sure which file you are using, if it's ipynb, u need jupyter notebook to load it, u can use jupyter notebook in visual studio. If it's py file, any python IDE can handle it. So you have to be more specific about what went wrong.

**Comment by Ajin695** [comment]
Good morning. The file i was talking about is in this link but it doesn’t work on my pc. I don’t know why, it gives me problem with Graph and that recall of the directory ‘ecole’. I don’t know what i should do https://github.com/je-suis-tm/graph-theory/blob/master/barabasi%20albert%20model.ipynb  
I need, basically, to build a Barabasi albert network and from the log log of the degree distribution, find that the power law with coefficient 3 is in agreement with the best fit curve... 
I hope you can help me, it's so important

**Comment by je-suis-tm** [comment]
It sounds to me that you do not know much about python as this is merely a directory problem. I would suggest u paste the full stack error traceback to ChatGPT and let it debug for u.
