### ISSUE TITLE
Option Trading Development

### ISSUE THREAD

**Issue by masteronecos** [je-suis-tm/je-suis-tm#13]
Hi there,

Amazing work with your Quant trading. 

I would like to discuss with you regarding a trading strategy development. 

Looking forward to hearing from you. 
 
 Please send me your contact details in case you’re interested to discuss this further.

Thanks

**Comment by je-suis-tm** [comment]
Hi, your description is a bit too vague. When you talk about strategy development, are we talking about brainstorming or an actual project? Why dont you leave your linkedin and I will see if our interest can match up?

**Comment by masteronecos** [comment]
Hi,

I am talking about an actual project.
https://www.linkedin.com/in/cosminpert/

My partner is one of the oldest option trades from Romania and he manages a
big portfolio.

We can arrange a call together and then decide if you will be interested in
working together.

Thank you,
