### ISSUE TITLE
Referral PhD

### ISSUE THREAD

**Issue by paritoshk** [je-suis-tm/je-suis-tm#2]
I would suggest checking out full-time faculty at Columbia Business school - Bruce Usher if you are interested in climate finance. I understand from your smart farmer, oil money, and ore money projects that could be an area of your interst. Feel free to email me if you want introduction.

**Comment by je-suis-tm** [comment]
Thanks Paritosh. I really appreciate your reaching out. It's just that I am actually pivoting my career from energy finance to applied mathematics and computational statistics. So I am really not that into climate finance like I used to be despite the fact that it's so chic. But that does not mean I will stop working on anything interesting in this area. Thank you for reading smart farmer and oil money! I guess I have to keep up the good work.

**Comment by paritoshk** [comment]
Sounds good! Computational statistics is definitely a critical area.
