### ISSUE TITLE
Are you open building a scraping Website?

### ISSUE THREAD

**Issue by dohtem1** [je-suis-tm/je-suis-tm#3]
Hello TM,

Checked out your repos, web scraping + Quant. Would you be open to building a data intensive website (example website: https://docoh.com).  Of course, you will be compensated for your time.  

Open to hiring a support to assist you if needed.  Frontend will be bootstrap ReactJS framework, and you will be working the backbone of the website.

This project will be more than interesting and challenging for you although experienced due to the website requires a bit more flavor (ML + Quant) integration and more...

Really hope you will consider working on this project. 

Ciao~

**Comment by je-suis-tm** [comment]
Sorry for the late reply, could you provide more context on what you are trying to achieve? I took a quick look at docoh. That website doesn't seem like ML+quant at all.

**Comment by dohtem1** [comment]
Thanks for your reply, 

Being this post being public,  could you email me so I can provide full detail including ML feature?  jmins500@gmail

**Comment by dohtem1** [comment]
Unable to open email due to incorrect pw.  Sent you an email, are you able to confirm?

**Comment by je-suis-tm** [comment]
I sent you my reply roughly two weeks ago but I haven't received any further incoming emails. Any further comments? Otherwise I will close the issue.

**Comment by dohtem1** [comment]
Oh!  I did not see any reaponse….  Reply email sent.
