### ISSUE TITLE
PhD Positions

### ISSUE THREAD

**Issue by cimsthom** [je-suis-tm/je-suis-tm#4]
Bonsoir Mademoiselle/Monsieur TM,

I was saw your quant-trading projects, then read the front page of your github. 

I am not sure if you are still looking for a PhD position. If so, you could consider registering an account here [https://www.bachelierfinance.org/](url), or here [https://siam.org/](url). They announce PhD and PostDoc opportunities periodically. It is the SIAM of the US, but I guess you could find similar ones in European countries. 

If you have already known, I am sorry for providing you those redundant information abruptly.

​Sincères Salutations

**Comment by je-suis-tm** [comment]
C'est une très bonne nouvelle!!! Merci beaucoup cimsthom!

**Comment by cimsthom** [comment]
How are you TM? How is the phd positions searching going?

**Comment by je-suis-tm** [comment]
Thanks for checking on me! I am doing well, u? I have been through a couple of interviews. To be honest, I still haven't found the one. At one point, I will have to compromise some of the targets I have in mind. So, I am still searching...
