### ISSUE TITLE
Hi Jesuis 

### ISSUE THREAD

**Issue by convertiblejay** [je-suis-tm/je-suis-tm#5]
I tried emailing you, but I am getting a failed mail delivery.

**Comment by je-suis-tm** [comment]
Hi convertiblejay, leave your email and I will contact you, may I ask what this is about?

**Comment by convertiblejay** [comment]
Hi Jesuis its about a python code I could use with I interactive brokers. my email is convertiblejay @ gmail.com I left the space on for obvious reasons
