### ISSUE TITLE
Bayesiano

### ISSUE THREAD

**Issue by flaviomamede** [je-suis-tm/je-suis-tm#6]
Boa tarde.
Infelizmente não sei nada de Python, mas entendo alguma coisa sobre investimentos.
Achei essa tese fantástica:
https://www.research-collection.ethz.ch/handle/20.500.11850/244960
Isso poderia ser implementado de modo mais acessível por nós aqui na terrinha brasilis.
Esse Tobias Setz era co-autor em muitos papers do Diethelm Wuertz, da RMetrics (https://www.rmetrics.org/), que tem muitos packages no R. Após o falecimento do dr. Wuertz, ele fundou a Adaptivv (https://www.adaptivv.com/) e administra 3 fundos, sendo um em cripto, usando sua técnica de "adivinhar" quando vai cair para segurar o fundo.
Muito bom.

Eu queria implementar uma estratégia com opções que aprendi, mas como não sei Python fica difícil.

Abrs e bom trabalho.

**Comment by je-suis-tm** [comment]
Hi, honestly I do not understand portuguese so I have to use google translate and I hope get a rough understanding. Thanks for sharing and I will take a look at Bayesian Change Point Models. My suggestion for you is to learn Python if you want to work in any industry, especially finance. R is only for academia.
