### ISSUE TITLE
How can I get in contact with you?

### ISSUE THREAD

**Issue by saileshp56** [je-suis-tm/je-suis-tm#8]
Hello, I was very interested by your article: https://je-suis-tm.github.io/graph-theory/portfolio-optimization/
And I wanted to ask you some questions about getting into quant development and the possibility of being a research assistant for you because I'm very impressed by all the work you do. Can we message one another somehow? My email to the address on your site failed.
My twitter is: https://twitter.com/unhingexd
I understand you're probably very busy, but if you could take the time to speak with me I'm sure I can do some very helpful work for you! Thanks a lot, also have you ever been published? I haven't seen some of your ideas anywhere else.

Thanks,
https://www.saileshp.com/
https://www.linkedin.com/in/saileshpola/

**Comment by je-suis-tm** [comment]
Thanks and apologies for the delayed reply @saileshp56 Unfortunately I am currently busy with other things and do not have the time to maintain this GitHub or any other stuff. If you really wanna learn more, my advice to you is simple, get a job in the industry. Whatever you can see in GitHub is only the tip of an iceberg. You only learn and grow in the real playground.
